name: NuGet
on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore
      run: dotnet restore OfferService.sln
      env:
        MIRKO_NUGET_USERNAME: ${{ github.actor }}
        MIRKO_NUGET_PWD: ${{ secrets.GITHUB_TOKEN }} # Oppure ${{ secrets.MIRKO_NUGET_PWD }}

    - name: Build
      run: dotnet build --configuration Release --no-restore OfferService.sln
      env:
        MIRKO_NUGET_USERNAME: ${{ github.actor }}
        MIRKO_NUGET_PWD: ${{ secrets.GITHUB_TOKEN }}

    - name: Pack
      run: dotnet pack --configuration Release --no-restore OfferService.sln

    - name: Push to GitHub Packages
      run: |
        dotnet nuget push "**/bin/Release/*.nupkg" \
          --api-key ${{ secrets.MIRKO_NUGET_PWD }} \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --skip-duplicate